tiy_class/Hospital_Tracker/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :hospitals do
    member do
      post :create_doctor
      delete :delete_doctor
    end
    resources :patients do 
      member do
        post :create_doctor
        delete :delete_doctor
      end
      resources :medications do 
      end
      member do
        put :waiting
        put :assessed
        put :xrayed
        put :operated
        put :paid
        put :discharged

      end
    end
  end

get '/patients' => 'patients#search_patients' 

end

tiy_class/Hospital_Tracker/app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients
  has_many :doctors, as: :doctorable
  validates :name, presence: true;
  geocoded_by :address
  after_validation :geocode  
end

tiy_class/Hospital_Tracker/app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
before_action :authenticate_user!, only: [:show, :new, :edit, :update, :destroy] 
before_action :find_hospital, only: [:show, :edit, :update, :destroy, :find_doctor, :create_doctor, :delete_doctor]
before_action :find_doctor, only: [:delete_doctor] 
  
  
  def index
    @hospital = Hospital.all
    @patient = Patient.all
  end

  def show
    @doctor = @hospital.doctors.new
    @patient = Patient.all
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.create hospital_params
    if @hospital.save == true
    redirect_to hospital_path(@hospital)
    else
    render :new
    end
  end

  def create_doctor
    @hospital.doctors.create doctor_params
    redirect_to @hospital
  end

  def delete_doctor
    @doctor.delete
    redirect_to hospital_path(@hospital)
  end

  def edit
  end

  def update
    @hospital.update_attributes hospital_params
    redirect_to hospitals_path(@hospital)
  end

  def destroy
    @hospital.delete
    redirect_to hospitals_path(@hospital)
  end

  private
  def find_hospital
    @hospital = Hospital.find params[:id]
  end
  def find_doctor
    @doctor = Doctor.find params[:doctor_id]
  end
  def hospital_params
    params.require(:hospital).permit(:name, :description, :address)
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

tiy_class/Hospital_Tracker/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

tiy_class/Hospital_Tracker/app/views/hospitals/_form.html.haml
= form_for @hospital do |f|
  = if f.object.errors.messages.length > 0
    <!-- Render the errors to the user -->
    = f.object.errors.messages.inspect  
    %br
      -f.object.errors.messages.each do |key, value| 
        -value.each do |message| 
          = key = message 
          %br
  = f.label :name
  = f.text_field :name, class: 'form-control focusedInput', placeholder: 'Add Name Here...'
  %br
  = f.label :description
  = f.text_area :description, class: 'form-control ', placeholder: 'Description...', rows: '3'
  = f.label :address
  = f.text_area :address, class: 'form-control ', placeholder: 'Address...', rows: '3'
  %br
  =f.submit "Create Hospital", class: 'btn btn-success btn-block'

tiy_class/Hospital_Tracker/app/views/hospitals/edit.html.haml
%h1 Edit Hospital
= render 'form'

tiy_class/Hospital_Tracker/app/views/hospitals/index.html.haml
%h1 Welcome to the Hospital Hub
%h2 Hospitals
%ul
-group_number = 0
%ul.col
  - @hospital.all.each_slice(10) do |group_hospital|
    -group_number += 1
    -group_hospital.each do |hospital|
      %li{class: "#{'hidden' if group_number >= 2} group_#{group_number} hospital_list"}
        =link_to hospital.name, hospital_path(hospital)
        %br
  -group_number.times do |x| 
    =link_to x + 1, 'javascript:void(0);', class: "new_page"

= link_to "Create Hospital", new_hospital_path, class: "btn btn-success btn-block"
=link_to "Tracker Home", root_path, class: "btn btn-primary btn-block"

tiy_class/Hospital_Tracker/app/views/hospitals/new.html.haml
%h1 New Hospital
= render 'form'
%ul.breadcrumb
  %li
    %a{:href => "../"} Tracker Home
  %li
    %a{:href => "/hospitals"} Hospital Hub
  %li.active New Hospital

tiy_class/Hospital_Tracker/app/views/hospitals/show.html.haml
%h1 Hospital Profile
%h4 Name: #{@hospital.name}
%h4 Description: #{@hospital.description}
%h4 Location: 
%img{:src => "http://maps.googleapis.com/maps/api/staticmap?center=#{@hospital.latitude},#{@hospital.longitude}&zoom=11&size=800x200"}/
%br
= link_to "| Edit Hospital |", edit_hospital_path(@hospital), class: "btn btn-xs btn-warning"
= link_to "| Delete Hospital |", hospital_path(@hospital), method: :delete, class: "btn btn-xs btn-danger"
%br
%br
= form_for @doctor, url: create_doctor_hospital_path(@hospital) do |f|
  %h4= f.label :name, "Doctor Name"
  %p= f.text_field :name, class: 'form-control focusedInput', placeholder: 'Add Name Here...'
  %p= f.submit "Add Doctor", class: 'btn btn-success btn-block'

%br
%h4 List of Doctors
- @hospital.doctors.each do |doctor|
  - if doctor.name 
    %p= doctor.name
    = link_to "| Delete Doctor |", delete_doctor_hospital_path(@hospital, doctor_id: doctor.id), method: :delete, class: "btn btn-xs btn-danger"
    %br
    %br
= link_to " Add Patient ", new_hospital_patient_path(@hospital), class: "btn btn-success btn-block"
%br
= text_field_tag '', '', class: "patient_search form-control focusedInput", placeholder: 'Search...'
= link_to "Search Patients", 'javascript:void(0);', class: "search_patients btn btn btn-primary btn-block"
%ul.search_list
-group_number = 0
%ul
  - @hospital.patients.each_slice(10) do |group_patient|
    -group_number += 1
    -group_patient.each do |patient|
      %li{class: "#{'hidden' if group_number >= 2} group_#{group_number} patient_list"}
        = link_to "#{patient.last_name}, #{patient.first_name}", hospital_patient_path(@hospital, patient)        
        %br
  -group_number.times do |x| 
    =link_to x + 1, 'javascript:void(0);', class: "new_page"

%ul.breadcrumb
  %li
    %a{:href => "../"} Tracker Home
  %li
    %a{:href => "/hospitals"} Hospital Hub
  %li.active New Hospital

      