tiy_class/hw_tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
resources :locations do
  resources :units do
    resources :projects do
      member do
        post :create_comment
        delete :delete_comment
      end    
      resources :transmits do
        member do
          post :create_comment
          delete :delete_comment
          put :submitted
          put :reviewed
          put :completed
          put :unsatisfactory
        end
      end
    end
  end
end

  root 'welcome#index'

end

tiy_class/hw_tracker/app/models/transmit.rb
class Transmit < ActiveRecord::Base
  belongs_to :projects
  belongs_to :users
  has_many :comments, as: :commentable
  include Workflow
  workflow do
   state :submitted do
      event :reviewing, transitions_to: :reviewed
      event :complete, transitions_to: :completed
      event :incomplete, transitions_to: :unsatisfactory
    end
    state :reviewed do
      event :complete, transitions_to: :completed
      event :incomplete, transitions_to: :unsatisfactory
    end
    state :completed do
      event :incomplete, transitions_to: :unsatisfactory
    end
    state :unsatisfactory do
      event :complete, transitions_to: :completed
    end
  end
end

tiy_class/hw_tracker/app/controllers/transmits_controller.rb
class TransmitsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_location
  before_action :find_unit
  before_action :find_project
  before_action :find_transmit, only:[:show, :edit, :update, :destroy, :create_comment, :delete_comment, :reviewed, :completed, :unsatisfactory]
  before_action :find_comment, only:[:delete_comment]
  def index
    @transmits = Transmit.all
  end

  def show
    @comment = @transmit.comments.new
  end

  def new
    @transmit = Transmit.new
  end

  def create
    @transmit = @project.transmits.create transmit_params
    if @transmit.save == true
    redirect_to location_unit_project_transmits_path(@location, @unit, @project, @transmit)
    else
    render :new
    end
  end

  def edit
  end

  def update
    @transmit.update_attributes transmit_params
    redirect_to location_unit_project_transmits_path(@location, @unit, @project, @transmit)
  end

  def destroy
    @transmit.delete
    redirect_to location_unit_path(@location, @unit)
  end

  def create_comment
    @comment = @transmit.comments.create comment_params.merge(user_id: current_user.id, first_name: current_user.first_name, last_name: current_user.last_name)
    redirect_to location_unit_project_transmit_path(@location, @unit, @project, @transmit)
  end

  def delete_comment
    @comment.delete
    redirect_to location_unit_project_transmit_path(@location, @unit, @project, @transmit)
  end

  def reviewed
    authorize! :reviewed, @transmit
    @transmit.reviewing!
    respond_to do |format|
      format.js
      format.html { redirect_to location_unit_project_transmit(@location, @unit, @project, @transmit) }
    end
  end

  def completed
    authorize! :completed, @transmit
    @transmit.complete!
    respond_to do |format|
      format.js
      format.html { redirect_to location_unit_project_transmit(@location, @unit, @project, @transmit) }
    end
  end

  def unsatisfactory
    authorize! :unsatisfactory, @transmit
    @transmit.incomplete!
    respond_to do |format|
      format.js
      format.html { redirect_to location_unit_project_transmit(@location, @unit, @project, @transmit) }
    end
  end


  private
  def transmit_params
    params.require(:transmit).permit(:name, :github_link, :heroku_link, :other_link, :content, :workflow_sate)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_location
    @location = Location.find params[:location_id]
  end

  def find_unit
    @unit = Unit.find params[:unit_id]
  end

  def find_project
    @project = Project.find params[:project_id]
  end

  def find_transmit
    @transmit = Transmit.find params[:id]
  end

  def find_comment
    @comment = @transmit.comments.find params[:comment_id]
  end
end

tiy_class/hw_tracker/app/helpers/transmits_helper.rb
module TransmitsHelper
end

tiy_class/hw_tracker/app/views/transmits/_form.html.haml
= form_for [@location, @unit, @project, @transmit] do |f|
  = if f.object.errors.messages.length > 0
    <!-- Render the errors to the user -->
    = f.object.errors.messages.inspect 
    %br
      -f.object.errors.messages.each do |key, value|
        -value.each do |message|
          = key = message
          %br
  = f.text_field :name, class: 'form-control focusedInput', placeholder: 'Add Project Name Here...'
  = f.text_area :github_link, class: 'form-control focusedInput', placeholder: 'Add GitHub URL Here...', rows: '5'
  = f.text_area :heroku_link, class: 'form-control focusedInput', placeholder: 'Add Heroku URL Here...', rows: '5'
  = f.text_area :other_link, class: 'form-control focusedInput', placeholder: 'Add Additional URLs Here...', rows: '5'
  = f.text_area :content, class: 'form-control focusedInput', placeholder: 'Add Project Content Here...', rows: '10'
  = f.submit
  %ul.breadcrumb
    %li
      =link_to "Home", root_path
    %li
      %a{:href => "/locations"} Location Portal
    %li
      = link_to 'Location Profile', location_path(@location)
    %li
      = link_to 'Unit Portal', location_units_path(@location)
    %li
      = link_to 'Unit Profile', location_unit_path(@location, @unit)
    %li
      = link_to 'Project Profile', location_unit_project_path(@location, @unit, @project)
    %li.active New Commit

tiy_class/hw_tracker/app/views/transmits/_workflow_partial.html.haml
Status: #{@transmit.workflow_state}
- if @transmit.workflow_state == "submitted" 
  = link_to "reviewed", 'javascript:void(0);', class: "put_status btn btn-xs btn-warning", workflow_state: "reviewed"
- elsif @transmit.workflow_state == "reviewed"
  = link_to "completed", 'javascript:void(0);', class: "put_status btn btn-xs btn-success", workflow_state: "completed"
  = link_to "unsatisfactory", 'javascript:void(0);', class: "put_status btn btn-xs btn-danger", workflow_state: "unsatisfactory"
- elsif @transmit.workflow_state == "unsatisfactory"
  = link_to "completed", 'javascript:void(0);', class: "put_status btn btn-xs btn-success", workflow_state: "completed"
- else @transmit.workflow_state == "completed"

tiy_class/hw_tracker/app/views/transmits/_workflow_status.js.erb
$("ul.put_status").html("")
  $("ul.put_status").append("<%= escape_javascript(render('patients/workflow_partial', transmit: @transmit)) %>")

tiy_class/hw_tracker/app/views/transmits/completed.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('transmits/workflow_partial', transmit: @transmit)) %>")

tiy_class/hw_tracker/app/views/transmits/edit.html.haml
%h1 Edit Commit
= render 'form'

tiy_class/hw_tracker/app/views/transmits/index.html.haml
%h1 Committed Files
- @project.transmits.each do |transmit|
  = link_to "#{transmit.name}", location_unit_project_transmit_path(@location, @unit, @project, transmit)
  = link_to "Edit", edit_location_unit_project_transmit_path(@location, @unit, @project, transmit), class: 'btn btn-xs btn-warning'
  = link_to "Delete", location_unit_project_transmit_path(@location, @unit, @project, transmit), method: :delete, class: 'btn btn-xs btn-danger'
  = transmit.workflow_state
  %br
%ul.breadcrumb
  %li
    =link_to "Home", root_path
  %li
    %a{:href => "/locations"} Location Portal
  %li
    = link_to 'Location Profile', location_path(@location)
  %li
    = link_to 'Unit Portal', location_units_path(@location)
  %li
    = link_to 'Unit Profile', location_unit_path(@location, @unit)
  %li
    = link_to 'Project Profile', location_unit_project_path(@location, @unit, @project)
  %li.active Committed Files

tiy_class/hw_tracker/app/views/transmits/new.html.haml
%h1 New Commit
= render 'form'

tiy_class/hw_tracker/app/views/transmits/reviewed.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('transmits/workflow_partial', transmit: @transmit)) %>")

tiy_class/hw_tracker/app/views/transmits/show.html.haml
%h1 Commit View
%ul.status_list
  =render "workflow_partial", transmit: @transmit 
%input{type: "hidden", value: @location.id, class: "location_id"}
%input{type: "hidden", value: @unit.id, class: "unit_id"}
%input{type: "hidden", value: @project.id, class: "project_id"}
%input{type: "hidden", value: @transmit.id, class: "transmit_id"}
%br
Name:
%br
= @transmit.name
%br
GitHub Link:
%br
= @transmit.github_link
%br
%br
Heroku Link:
%br
= @transmit.heroku_link
%br
%br
Additional URL
%br
= @transmit.other_link
%br
%br
Content:
%br
= @transmit.content
%br
%br
-@transmit.comments.each do |comment|
  -if comment.content
    = comment.first_name
    = comment.last_name
    %br
    = comment.content
    = link_to "Delete", delete_comment_location_unit_project_path(@location, @unit, @project, comment_id: comment.id), method: :delete
    %br
    %br
%br
= form_for @comment, url: create_comment_location_unit_project_transmit_path(@location, @unit, @project, @transmit) do |f|
  = f.text_area :content, class: 'form-control focusedInput', placeholder: 'Add Comment Here...'
  %br
  = f.submit
  %br
%ul.breadcrumb
  %li
    =link_to "Home", root_path
  %li
    %a{:href => "/locations"} Location Portal
  %li
    = link_to 'Location Profile', location_path(@location)
  %li
    = link_to 'Unit Portal', location_units_path(@location)
  %li
    = link_to 'Unit Profile', location_unit_path(@location, @unit)
  %li
    = link_to 'Project Profile', location_unit_project_path(@location, @unit, @project)
  %li.active Commit View

tiy_class/hw_tracker/app/views/transmits/unsatisfactory.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('transmits/workflow_partial', transmit: @transmit)) %>")