tiy_class/hw_tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models
resources :locations do
  resources :units do
    resources :projects do
      member do
        post :create_comment
        delete :delete_comment
      end    
      resources :transmits do
        member do
          post :create_comment
          delete :delete_comment
          put :submitted
          put :reviewed
          put :completed
          put :unsatisfactory
        end
      end
    end
  end
end

  root 'welcome#index'

end

tiy_class/hw_tracker/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :unit
  has_many :transmits
  has_many :comments, as: :commentable
end

tiy_class/hw_tracker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_location
  before_action :find_unit
  before_action :find_project, only: [:show, :edit, :update, :destroy, :create_comment, :delete_comment]
  before_action :find_comment, only: [:delete_comment] 
  def index
    @projects = Project.all
  end

  def show
    @comment = @project.comments.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = @unit.projects.create project_params
    if @project.save == true 
    redirect_to location_unit_path(@location, @unit)
    else 
    render :new
    end
  end

  def edit
  end

  def update
    @project.update_attributes project_params
    redirect_to location_unit_path(@location, @unit)
  end

  def destroy
    @project.delete
    redirect_to location_unit_path(@location, @unit)
  end

  def create_comment
    @comment = @project.comments.create comment_params.merge(user_id: current_user.id, first_name: current_user.first_name, last_name: current_user.last_name)
    redirect_to location_unit_project_path(@location, @unit, @project)
  end

  def delete_comment
    @comment.delete
    redirect_to location_unit_project_path(@location, @unit, @project)
  end

  private
  def project_params
  params.require(:project).permit(:name, :date, :description, :requirements, :workflow_state)
  end

  def comment_params
    params.require(:comment).permit(:content, :commentable_type, :commentable_id, :first_name, :last_name)
  end

  def find_location
  @location = Location.find params[:location_id]
  end

  def find_unit
  @unit = Unit.find params[:unit_id]
  end

  def find_project
  @project = Project.find params[:id]
  end

  def find_comment
    @comment = @project.comments.find params[:comment_id]
  end

end

tiy_class/hw_tracker/app/helpers/projects_helper.rb
module ProjectsHelper
end

tiy_class/hw_tracker/app/views/projects/_form.html.haml
= form_for [@location, @unit, @project] do |f|
  = if f.object.errors.messages.length > 0
    <!-- Render the errors to the user -->
    = f.object.errors.messages.inspect  
    %br
      -f.object.errors.messages.each do |key, value| 
        -value.each do |message| 
          = key = message 
          %br
  = f.text_field :name, class: 'form-control focusedInput', placeholder: 'Add Project Name Here...'
  = f.date_select(:date, :start_year => 1900)
  = f.text_area :description, class: 'form-control focusedInput', placeholder: 'Add Project Description Here...', rows: '10'
  = f.text_area :requirements, class: 'form-control focusedInput', placeholder: 'Add Project Requirements Here...', rows: '10'
  =f.submit "Add Project", class: 'btn btn-success btn-block'

tiy_class/hw_tracker/app/views/projects/edit.html.haml
%h1 Edit Projects
= render 'form'

tiy_class/hw_tracker/app/views/projects/index.html.haml
%h1 Projects
- @unit.projects.each do |project|
  = link_to "#{project.name}", location_unit_project_path(@location, @unit, project)
  = link_to "Edit", edit_location_unit_project_path(@location, @unit, project), class: 'btn btn-xs btn-warning'
  = link_to "Delete", location_unit_project_path(@location, @unit, project), method: :delete, class: 'btn btn-xs btn-danger'

tiy_class/hw_tracker/app/views/projects/new.html.haml
%h1 New Project
= render 'form'
%ul.breadcrumb
  %li
    =link_to "Homework Tracker Home", root_path
  %li
    %a{:href => "/locations"} Location Portal
  %li
    = link_to 'Location Profile', location_path(@location)
  %li
    = link_to 'Unit Portal', location_units_path(@location)
  %li
    = link_to 'Unit Profile', location_unit_path(@location, @unit)
  %li.active New Project

tiy_class/hw_tracker/app/views/projects/show.html.haml
%h1 Project
Name:
%br
= @project.name
%br
Date Assigned:
%br
= @project.date
%br
%br
Project Description:
%br
= @project.description
%br
%br
Project Requirements: 
%br
= @project.requirements
%br
= link_to "Make a Commit", new_location_unit_project_transmit_path(@location, @unit, @project), class: 'btn btn-info btn-block'
= link_to "See Commits", location_unit_project_transmits_path(@location, @unit, @project, @transmit), class: 'btn btn-info btn-block'
%br
-@project.comments.each do |comment|
  -if comment.content
    = comment.first_name
    = comment.last_name
    %br
    = comment.content
    = link_to "Delete", delete_comment_location_unit_project_path(@location, @unit, @project, comment_id: comment.id), method: :delete
    %br
    %br
%br
= form_for @comment, url: create_comment_location_unit_project_path(@location, @unit, @project) do |f|
  = f.text_area :content, class: 'form-control focusedInput', placeholder: 'Add Comment Here...'
  %br
  = f.submit

%br
%ul.breadcrumb
  %li
    =link_to "Homework Tracker Home", root_path
  %li
    %a{:href => "/locations"} Location Portal
  %li
    = link_to 'Location Profile', location_path(@location)
  %li
    = link_to 'Unit Portal', location_units_path(@location)
  %li
    = link_to 'Unit Profile', location_unit_path(@location, @unit)
  %li.active Project Profile