tiy_class/Hospital_Tracker/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :hospitals do
    member do
      post :create_doctor
      delete :delete_doctor
    end
    resources :patients do 
      member do
        post :create_doctor
        delete :delete_doctor
      end
      resources :medications do 
      end
      member do
        put :waiting
        put :assessed
        put :xrayed
        put :operated
        put :paid
        put :discharged

      end
    end
  end

get '/patients' => 'patients#search_patients' 

end

tiy_class/Hospital_Tracker/app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :medications
  has_many :doctors, as: :doctorable
  belongs_to :hospital
  include Workflow
  workflow do
   state :waiting do
      event :assess, transitions_to: :assessed
      event :xray, transitions_to: :xrayed
      event :operate, transitions_to: :operated
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end
   state :assessed do
      event :xray, transitions_to: :xrayed
      event :operate, transitions_to: :operated
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end
  state :xrayed do
      event :assess, transitions_to: :assessed
      event :operate, transitions_to: :operated
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end
  state :operated do
      event :assess, transitions_to: :assessed
      event :xray, transitions_to: :xrayed
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end
  state :paid do
      event :discharge, transitions_to: :discharged
    end
  state :discharged
    end 
validates :first_name, presence: true;
validates :last_name, presence: true;
validates_date :DOB, :before => lambda { Date.current }
validates :description, presence: true;
validates :gender, presence: true;
end

tiy_class/Hospital_Tracker/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :authenticate_user!
before_action :find_hospital, except: [:search_patients]
before_action :find_patient, only: [:show, :edit, :update, :destroy, :waiting, :assessed, :xrayed, :operated, :paid, :discharged,:find_doctor, :create_doctor, :delete_doctor]

  def index
    @patient = Patient.all 
  end
  
  def search_patients
    @patient = Patient.where("last_name LIKE ?", "%#{params[:q]}%")
    respond_to do |format|
      format.js
    end
  end
  
  def new
    @patient = Patient.new
  end

  def show
    @doctor = @patient.doctors.new 
  end

  def create
    @patient = @hospital.patients.create patients_params
    if @patient.save == true
    redirect_to hospital_patient_path(@hospital, @patient)
    else
    render :new
    end
  end

  def edit
  end

  def update
    @patient.update_attributes patients_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def destroy
    @patient.delete
    redirect_to hospital_path(@hospital)
  end

  def waiting
    @patient.waiting!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def assessed
    @patient.assess!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def xrayed
    @patient.xray!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def operated
    @patient.operate!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def paid
    @patient.pay!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def discharged
    @patient.discharge!
    respond_to do |format|
      format.js
      format.html { redirect_to hospital_patient_path(@hospital, @patient) }
    end
  end

  def create_doctor
    @doctor = @patient.doctors.create doctor_params
    redirect_to hospital_patient_path
  end

  def delete_doctor
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:id]
    @doctor = Doctor.find params[:doctor_id]
    @doctor.delete
    redirect_to hospital_patient_path
  end

  private
  def find_doctor
    @doctor = Doctor.find params[:doctor_id]
  end
  def find_patient
    @patient = Patient.find params[:id]
  end
  def find_hospital
    @hospital = Hospital.find params[:hospital_id]
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end
  def patients_params
    params.require(:patient).permit(:first_name, :last_name, :DOB, :gender, :description, :workflow_state)
  end
end

tiy_class/Hospital_Tracker/app/helpers/patients_helper.rb
module PatientsHelper
end

tiy_class/Hospital_Tracker/app/views/patients/_form.html.haml
= form_for [@hospital, @patient] do |f|
  = if f.object.errors.messages.length > 0
    <!-- Render the errors to the user -->
    = f.object.errors.messages.inspect  
    %br
      -f.object.errors.messages.each do |key, value| 
        -value.each do |message| 
          = key = message 
          %br
  = f.text_field :first_name, class: 'form-control focusedInput', placeholder: 'Add First Name Here...'
  = f.text_field :last_name, class: 'form-control focusedInput', placeholder: 'Add Last Name Here...'
  = f.label "Male"
  = f.radio_button :gender, "Male"
  = f.label "Female"
  = f.radio_button :gender, "Female"
  %br
  = f.label :DOB, "Date of Birth"
  = f.date_select( :DOB, :start_year => 1900)
  = f.text_area :description, class: 'form-control ', placeholder: 'Description...', rows: '3'
  = f.submit "Add Patient", class: 'btn btn-success btn-block'

tiy_class/Hospital_Tracker/app/views/patients/_patient_partial.html.haml
%li
  =patient.first_name
  =patient.last_name

  =link_to 'Patient Profile', hospital_patient_path(patient.hospital, patient), class: "btn btn-xs btn-info"

tiy_class/Hospital_Tracker/app/views/patients/_workflow_partial.html.haml
%p Status: #{@patient.workflow_state}
- if @patient.workflow_state == "waiting"
  = link_to "assessed", 'javascript:void(0);', class: "put_status btn btn-xs btn-primary", workflow_state: "assessed"
  = link_to "xrayed", 'javascript:void(0);', class: "put_status btn btn-xs btn-info", workflow_state: "xrayed"
  = link_to "operated", 'javascript:void(0);', class: "put_status btn btn-xs btn-danger", workflow_state: "operated"
- elsif @patient.workflow_state == "assessed"
  = link_to "xrayed", 'javascript:void(0);', class: "put_status btn btn-xs btn-info", workflow_state: "xrayed"
  = link_to "operated", 'javascript:void(0);', class: "put_status btn btn-xs btn-danger", workflow_state: "operated"
  = link_to "paid", 'javascript:void(0);', class: "put_status btn btn-xs btn-warning", workflow_state: "paid"
- elsif @patient.workflow_state == "xrayed"
  = link_to "paid", 'javascript:void(0);', class: "put_status btn btn-xs btn-warning", workflow_state: "paid"
- elsif @patient.workflow_state == "operated"
  = link_to "paid", 'javascript:void(0);', class: "put_status btn btn-xs btn-warning", workflow_state: "paid"
- elsif @patient.workflow_state == "paid"
  = link_to "discharged", 'javascript:void(0);', class: "put_status btn btn-xs btn-success", workflow_state: "discharged"
- else @patient.workflow_state == "discharged"
  = link_to "| Add Final Notes |", edit_hospital_patient_path(@hospital, @patient), class: "put_status btn btn-xs btn-success"

tiy_class/Hospital_Tracker/app/views/patients/assessed.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")

tiy_class/Hospital_Tracker/app/views/patients/discharged.js.erb
$("ul.status_list").html("")
  $("ul.stauts_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")

tiy_class/Hospital_Tracker/app/views/patients/edit.html.haml
%h1 Edit Patient
= render 'form'

tiy_class/Hospital_Tracker/app/views/patients/index.html.haml
/ %h1 Welcome to Patient Portal
/ = link_to "Create Patient", new_hospital_patient_path
/ %ul
/   Patients
/   - @patients.each do |patient|
/     %li
/       = link_to "#{@patient.last_name}, #{@patient.first_name}", hospital_patient_path(hospital)
/       = link_to "| Edit Patient |", edit_hospital_patient_path(patient)
/       = link_to "| Delete Patient |", hospital_patient_path(patient), method: :delete
      
/       |
/       = patient.workflow_state
/       |
/     - if @patient.workflow_state == "waiting"
/       = link_to "assessed", waiting_patient_path(patient), method: :put
/       = link_to "xrayed", xrayed_patient_path(patient), method: :put
/       = link_to "operated", operated_patient_path(patient), method: :put
/     - if @patient.workflow_state == "assessed"
/       = link_to "xrayed", xrayed_patient_path(patient), method: :put
/       = link_to "operated", operated_patient_path(patient), method: :put
/       = link_to "paid", paid_patient_path(patient), method: :put
/     - if @patient.workflow_state == "xrayed"
/       = link_to "operated", operated_patient_path(patient), method: :put
/       = link_to "paid", paid_patient_path(patient), method: :put
/     - if @patient.workflow_state == "operated"
/       = link_to "paid", paid_patient_path(patient), method: :put
/     - if @patient.workflow_state == "paid"
/       = link_to "discharged", discharged_patient_path(patient), method: :put
/     - if @patient.workflow_state == "discharged"
/       = link_to "|Add Final Notes|", edit_hospital_patient_path(patient)    

tiy_class/Hospital_Tracker/app/views/patients/new.html.haml
%h1 New Patient
= render 'form'
%ul.breadcrumb
  %li
    %a{:href => "../"} Tracker Home
  %li
    %a{:href => "/hospitals"} Hospital Hub
  %li
    = link_to 'Hospital Homepage (back)', hospital_path(@hospital)
  %li.active New Patient

tiy_class/Hospital_Tracker/app/views/patients/operated.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")

tiy_class/Hospital_Tracker/app/views/patients/paid.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")

tiy_class/Hospital_Tracker/app/views/patients/search_patients.js.erb
$("ul.search_list").html("")
<% @patient.each do |patient| %>
  $("ul.search_list").append("<%= escape_javascript(render('patients/patient_partial', patient: patient)) %>")
<% end %>

tiy_class/Hospital_Tracker/app/views/patients/show.html.haml
%h1 Patient Profile
%p First Name: #{@patient.first_name}
%p Last Name: #{@patient.last_name}
%p Gender: #{@patient.gender}
%p Date of Birth: #{@patient.DOB}
%p Notes: #{@patient.description}
%ul.status_list
  =render "workflow_partial", patient: @patient 
%input{type: "hidden", value: @hospital.id, class: "hospital_id"}
%input{type: "hidden", value: @patient.id, class: "patient_id"}
%br 
%br
= link_to "| Edit Patient |", edit_hospital_patient_path(@hospital, @patient), class: 'btn btn-s btn-warning'
= link_to "| Delete Patient |", hospital_patient_path(@hospital, @patient), method: :delete, class: 'btn btn-s btn-danger'
%br
%br
- @patient.doctors.each do |doctor|
  - if doctor.name 
    %p= doctor.name
    = link_to "| Delete Doctor |", delete_doctor_hospital_patient_path(@hospital, @patient, doctor_id: doctor.id), method: :delete, class: "btn btn-xs btn-danger"
    %br
  %br
= form_for @doctor, url: create_doctor_hospital_patient_path(@hospital, @patient) do |f|
  = f.label :name
  = f.text_field :name, class: 'form-control focusedInput', placeholder: 'Add Name Here...'
  = f.submit "Add Doctor", class: 'btn btn-success btn-block'
%br
%br
= link_to "Add Medication", new_hospital_patient_medication_path(@hospital, @patient), class: 'btn btn-success'
%br
-group_number = 0
%ul
  - @patient.medications.each_slice(5) do |group_medication|
    -group_number += 1
    -group_medication.each do |medication|
      %li{class: "#{'hidden' if group_number >= 2} group_#{group_number} medication_list"}
        = link_to "#{medication.name}", hospital_patient_medication_path(@hospital, @patient, medication)
        %br
  -group_number.times do |x| 
    =link_to x + 1, 'javascript:void(0);', class: "new_page"
%ul.breadcrumb
  %li
    %a{:href => "../"} Tracker Home
  %li
    %a{:href => "/hospitals"} Hospital Hub
  %li
    = link_to 'Hospital Homepage (back)', hospital_path(@hospital)
  %li.active Patient Profile

tiy_class/Hospital_Tracker/app/views/patients/workflow_status.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")

tiy_class/Hospital_Tracker/app/views/patients/xrayed.js.erb
$("ul.status_list").html("")
  $("ul.status_list").append("<%= escape_javascript(render('patients/workflow_partial', patient: @patient)) %>")